_internal:
    type: group
    route: /_internal
    routes:
        javascript:
            route: /js/{filename:string}
            controller: Sebastian\Internal:InternalController
            method: getJS